sqlalchemy.exc.ProgrammingError: (pyodbc.ProgrammingError) ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'PM_TOT_AMPS'. (207) (SQLExecDirectW)")
[SQL: 
            SELECT Data_Time, [PM_TOT_AMPS] AS Value
            FROM PI_REPLICATION.dbo.Summary_Daily_AVG_TC_PEM_Melting_1
            WHERE Data_Time BETWEEN '2024-01-01 00:00:00' AND '2024-11-05 00:00:00'
            ORDER BY Data_Time
        ]
(Background on this error at: https://sqlalche.me/e/20/f405)
